### ISSUE TITLE
Shining Force Final Conflict Game Gear English trad

### ISSUE THREAD

**Issue by gameblabla** [negativeExponent/smsplus-gx_libretro#25]
Hello,
there's an issue with SMS Plus GX (including my fork, and including Mednafen too) with Shining Force Final Conflict with the english translation.
If you boot the game, as soon as you get to the narrator, it will either freeze or sometimes even crash too.
I eventually found a hack fix of sorts after i found out that the older SMS Plus could play the game too:
https://github.com/gameblabla/sms_sdl/commit/cb1a393d998d3fb40b0d3059dd8335a81a5ede71

You might think this is an issue related to the mapping code but it's not. It's caused by something else (that is also not a CPU bug as it happened on Eighty Z80 and it's literally the same Z80 ad MAME's).
I was hoping to find a proper fix to this though, instead of a hack.
Any ideas ? :/

**Comment by negativeExponent** [comment]
According to GPGX, the translation uses SEGA MAPPER without bankswitching

https://github.com/libretro/Genesis-Plus-GX/blob/eba9bf57143de17115dce82bb969a111c1218e61/core/cart_hw/sms_cart.c#L91-L92

https://github.com/libretro/Genesis-Plus-GX/blob/master/core/cart_hw/sms_cart.c#L1134

so, your hack should not be a hack then.

**Comment by gameblabla** [comment]
Ah, good to know. I pushed another commit to clarify that.
Is there a way of contacting ekeeke btw ? (other than github)

**Comment by negativeExponent** [comment]
discord probably, or just leave a message for him on his git page
